targets:
  dev:
    variables:
      env: DEV
      instance_pool_id: "0212-053758-koala2-pool-jblwnzqa" 
      cluster_policy_id: "000CFA8A87B93FCD"

    #permissions:
      #- group_name: users
        #level: CAN_RUN
      #- group_name: users
       # level: CAN_VIEW

    mode: development
    
    workspace:
      host: https://adb-7405610441891523.3.azuredatabricks.net
      # Explicitly use your profile to avoid the 'Multiple Profiles' error
      profile: db-dev
      root_path: /Workspace/Users/neehas187@gmail.com/DAB_Check
    
    # This solves your notebook access error!
    run_as:
      user_name: ${workspace.current_user.userName}

    presets:
      trigger_pause_status: PAUSED